package main

import (
	"fmt"
	"monoalphabetic/caesar"
)

func main() {
	messages := []string{
		"DNWADFEFUD",
		"MBSZDYQBKPSK",
		"WLUZVSVNVLEPZAV",
		"REQXFXVZEQXYXTLTDFE",
		"JWXTYFMQYWOWHYGWMYOM",
		"QNBETIOEVCQAIRBINIKIIL",
		"ALCDELPQWAOLDDLTNHLALNVNIWQVNCDENLHVN",
		"QWKQCEBUUCFUTHQTKHQJQDJERQJUQJUGKUVKHQ",
		"TIXKLBLMXGVBTXHVTFBGAHWHXQBMHFTLTITVBXGVBTXHLXZKXWHWHXJNBEBUKBH",
		"OBEBODBEPUFNQPRVFNBQSFOEFBWJWFSPQSFTFOUFFODPOUSBBWFSEBEFJSBMJCFSEBEF",
		"WNEPMLXDHXZEPEDHEZREATDRXREOTLGEKVNHTZREKELYOYRXREEMXJXTLTDFTRXITVDXRX",
		"NSBEPNQRHZEVBANBRFGNRZFHNIRYBPVQNQRZNFRZFHNQRGREZVANPNBQRFRETHVENQVNAGR",
		"ZUMOSZFWYXOEMJZMWVTZWXVYZBWHMSEFZFWXZVWXVYZFWTWOXEJZSZMFWVWONYEOZFEZJTW",
		"QUFGUCHKQUFCXKFCUCQKPGXKVCKUOCUGPHTGPVCNQUEQOEQTCIGOPQUVQTPCKPXGPEKXGKU",
		"ELZTMEMZJTEEOJCEMZZFKOKAOEWKJETETEMJSJFJRMZZNFKNGTETOEUYTZFJKUEQAENMKFARGJLEME",
		"EQJQRQDTYQPLOVQYEKPILQKRKVZIYTJQJPRQVQPGEVPAPVILQCTGZKVTQXIPAQFPQRPYQGPVFPLOVQJQ",
		"ZBTQHNRHCZCDRNAQDZUHCZDLSNCNRNRRDTRZRODBSNRBNMSHMTZRDMCNRDFQDCNCNRFQZMCDRBQHZCNQDR",
		"AHTDNEGCAEGXMTGUHVODNPPDOFOHDJFDPFNDRJSXEACTUFGOEBEXMVNDMBUSEMQLMQCFTPRRSJVLVPSXETWDSBEREYGUCFOQAWKGAECVPFUVOBUDETGXRFFRRQGOOMGJAEQGECQQDBFHQVGHLFFHIYCSASQIUUWUO",
		"PDDPAIPDZGSDGZFSBSPDPDUPEKZGUGXKBKXSAGVBGABGNKSDGUXSZKSXGNSDOGZGDDGPBPADOXMSEPDUGDDPGUGDDPBPZXKDSVSKABSGYKSAGFGVGNKVKMZGUGSQGPSABGADGNKVUPXOXGADYPXZGXCKOGDKZXKGVSEGEKBPABXKOG",
		"VRUVAEUSYMGYGSUINKAFRVKEZKGQVRYSMMVPRXFHZAUFFXRGPTUWZEJXVUHIZHVVZDKPNIRSZAVVBJLRYIYUHIGIMUOXRQRGVLGTRWJSVKUQCVVIILKVZICLJZYYNWGSOMTGVECMYIJIFPZQDBKWRSMIMLGHRMISKCXTBWVHZMDMFXVRXQG",
		"MZNQXCVQKIATMGHHPQVPXVEMHNLIYKWAMVLZMDNMWQJEBSPFQTXGZZMTXQAZIRGJCMVGTVZALRLEQQWFVSXLMGXVXQVNVEZXIPBIYKQNIVLKWZIVPMVQXVZAUBFIYBWFWMQQKVXMDIJRWSCQICTVLKMYXFCIZNLTPYCRGEDKWAJYTABNLHTIZVTW",
	}

	// Caesar test
	for shift := 1; shift <= 26; shift++ {
		fmt.Printf("Shift %d:\n", shift)
		for _, message := range messages {
			caesar_decryption := caesar.CeasarDecript(message, shift)
			fmt.Println(caesar_decryption)
		}
		fmt.Println()
	}
}
